name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Create dummy firebase_options.dart
        run: |
          echo "import 'package:firebase_core/firebase_core.dart';
          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              return const FirebaseOptions(
                apiKey: 'dummy',
                appId: 'dummy',
                messagingSenderId: 'dummy',
                projectId: 'dummy',
              );
            }
          }" > lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
